name: Python package for qase

on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: true
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: true
      qase_project_code:
        description: 'Qase project code'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: true
      qase_run_complete:
        description: 'Complete Qase Run'
        required: true

env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  QASE_REPORT: ${{ inputs.qase_report }}
  QASE_PROJECT_CODE: ${{ inputs.qase_project_code }}
  QASE_RUN_ID: ${{ inputs.qase_run_id }}
  QASE_RUN_COMPLETE: ${{ inputs.qase_run_complete }}
  QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  
jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
      - uses: qase-tms/qase-link-run@main
        env:
          QASE_API_TOKEN: ${{ env.QASE_API_TOKEN }}
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.11, '3.10', 3.9, 3.8, 3.7]
        changed-dir: ["qaseio", "qase-pytest", "qase-robotframework", "qase-python-commons"]
    name: Project ${{ matrix.changed-dir }} - Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: 'shell'
        filters: |
          changes:
            - '${{ matrix.changed-dir }}/**'
    - name: Set up Python ${{ matrix.python-version }}
      if: steps.filter.outputs.changes == 'true'
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      if: steps.filter.outputs.changes == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Lint with tox
      if: steps.filter.outputs.changes == 'true'
      working-directory: ./${{ matrix.changed-dir }}
      run: |
        tox
  build-n-publish:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      max-parallel: 1
      matrix:
        prefix: [ "qaseio", "qase-pytest", "qase-robotframework", "qase-python-commons" ]
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      if: contains(github.event.ref, matrix.prefix)
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Build a binary wheel and a source tarball
      if: contains(github.event.ref, matrix.prefix)
      working-directory: ./${{ matrix.prefix }}
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: Publish distribution to PyPI
      if: contains(github.event.ref, matrix.prefix)
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        password: ${{ secrets.PYPI_PASSWORD }}
        packages_dir: ./${{ matrix.prefix }}/dist
